version: '3.7'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
    container_name: node-app
    ports:
      - '3001:3001'
    command: sh -c "npm install -f && npm run tsc && node ./build/index.js"
